# Generated by Django 5.2.3 on 2025-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_id', models.CharField(max_length=100)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(upload_to='found_ids/')),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
