# Generated by Django 5.2.3 on 2025-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundid',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
