# Generated by Django 5.2.3 on 2025-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idFinder', '0002_alter_foundid_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostIDReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('last_seen_location', models.CharField(max_length=200)),
                ('contact_info', models.CharField(blank=True, help_text='Optional phone/email', max_length=150)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
