# Generated by Django 5.2.3 on 2025-06-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idFinder', '0003_lostidreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LostReport',
        ),
    ]
